version: '3.8'
services:
  trivia-maze:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./cool trivia maze/:/app"   # project
      - "./dist:/output"             # exports copied here by start.sh
    environment:
      - DISPLAY=:0
    command: ["/start.sh", "windows"]  # or "linux" / "web"
